---
- hosts: database
  become: true
  tasks:
    - name: get mysql57 package
      get_url:
        url: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
        dest: /home/ec2-user/mysql57-community-release-el7-11.noarch.rpm

    - name: Install mysql57 package
      yum:
        name: /home/ec2-user/mysql57-community-release-el7-11.noarch.rpm
        state: present

    - name: install the latest version of mysql-community-server
      yum:
        name: mysql-community-server
        state: present

    - name: ensure mysql-community-server started
      service: name=mysqld state=started enabled=yes


# sudo wget https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
# sudo yum localinstall mysql57-community-release-el7-11.noarch.rpm 
# sudo yum install mysql-community-server
# systemctl start mysqld.service