version: '3.1'

services:
  lb01:
    image: ubuntu:latest
    stdin_open: true
    tty: true
  app01-app02:
    image: ubuntu:latest
    stdin_open: true
    tty: true
  db01:
    image: ubuntu:latest
    stdin_open: true
    tty: true
networks:
  default:
    external:
      name: dockerbased_control_network