version: '3.1'

services:
  lb01:
    build: Dockerfile
    image: ubuntuansible:latest
    # stdin_open: true
    # tty: true
    ports: 
      - "32768:22"
      - "8080:80"
  app01:
    build: Dockerfile
    image: ubuntuansible:latest
    ports: 
      - "32767:22"
      - "80:80"
  app02:
    build: Dockerfile
    image: ubuntuansible:latest
    ports: 
      - "32766:22"
      - "81:80"
  db01:
    build: Dockerfile
    image: ubuntuansible:latest
    ports: 
      - "32765:22"
networks:
  default:
    external:
      name: dockerbased_control_network