FROM centos:7

RUN mkdir -p /home/ansible
WORKDIR /home/ansible
RUN yum -y install ansible
ARG name=ansiblecentos

# CMD ["yum", "-y", "install", "ansible"]
# docker run -it -v ${PWD}:/home/ansible ede4081c5ec9
