---
# Bring stack down
- hosts: loadbalancer
  become: true
  tasks:
    - name: Bringing down nginx
      service: name=nginx state=stopped
      

- hosts: webserver
  become: true
  tasks:
    - name: Bringing down apache2
      service: name=apache2 state=stopped

# Restart mysqld
- hosts: database
  become: true
  tasks:
    - name: restarting database
      service: name=mysql state=restarted

# Bring stack up
- hosts: webserver
  become: true
  tasks:
    - name: Bringing started apache2
      service: name=apache2 state=started

- hosts: loadbalancer
  become: true
  tasks:
    - name: Bringing started nginx
      service: name=nginx state=started